
name: Test PowerShell on Ubuntu
on: [ workflow_dispatch ]
    inputs:
      issue-number:
        description: issue number
        required: true
env:
  MY_SECURET_HOGE1: ${{secrets.MY_SECURET_HOGE1}}

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-Path resultsfile.log | Should -Be $true
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester Unit.Tests.ps1 -Passthru
#          Invoke-Pester Unit.Tests.ps1 -OutputFile ./test-results.xml -OutputFormat NUnitXml
      - name: sample scr word out
        shell: pwsh
        if: github.event.inputs.issue-number == '1'
        run: |
            write-host "output:"
             $MY_SECURET_HOGE1
